# Generated by Django 4.1.1 on 2022-11-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_banner_brandslogan_banner_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='Brandname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
