# Generated by Django 4.1.1 on 2022-11-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_banner_brandname'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandaAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='photos/brandad')),
                ('alt_text', models.CharField(max_length=300)),
                ('caption', models.CharField(max_length=50)),
                ('Brandname', models.CharField(max_length=100)),
            ],
        ),
    ]
