# Generated by Django 4.1.2 on 2022-11-30 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_brandaad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrandaAd',
            new_name='BrandAd',
        ),
    ]
