# Generated by Django 4.1.2 on 2022-12-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_brandaad_brandad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=1, upload_to='userprofile'),
            preserve_default=False,
        ),
    ]
