# Generated by Django 4.1.2 on 2022-11-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_multipleimages'),
        ('order', '0006_orderitem_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation',
            field=models.ManyToManyField(to='store.variation'),
        ),
    ]
