# Generated by Django 4.1.2 on 2022-11-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out For Shipping', 'Out For Shipping'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Shipped', 'shipped'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
