<<<<<<< Updated upstream
# Generated by Django 4.1.2 on 2022-12-04 13:56
=======
# Generated by Django 4.1.2 on 2022-12-01 07:45
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
<<<<<<< Updated upstream
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Out For Shipping', 'Out For Shipping'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=150),
=======
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Out For Shipping', 'Out For Shipping'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=150),
>>>>>>> Stashed changes
        ),
    ]
