# Generated by Django 4.1.2 on 2022-12-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out For Shipping', 'Out For Shipping'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=150),
        ),
    ]
