# Generated by Django 4.1.1 on 2022-10-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regform',
            old_name='mobile_number',
            new_name='phone_number',
        ),
    ]
