# Generated by Django 4.1.1 on 2022-11-24 03:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_rename_reviewrating_reviewratings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewRatings',
            new_name='ReviewRating',
        ),
    ]
