# Generated by Django 4.1.2 on 2022-11-28 11:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_reviewratings_reviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(max_length=200, unique=True),
        ),
    ]
