# Generated by Django 4.1.1 on 2022-11-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
