# Generated by Django 4.1.2 on 2022-10-30 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
