# Generated by Django 4.1.1 on 2022-11-13 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('cat_image', models.ImageField(blank=True, upload_to='photos/categories')),
                ('count_sold', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'main_category',
                'verbose_name_plural': 'main_categories',
            },
        ),
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='cat_image',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.main_category'),
        ),
    ]
