# Generated by Django 4.1.1 on 2022-11-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_main_category_category_main_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='main_category',
        ),
        migrations.DeleteModel(
            name='Main_Category',
        ),
    ]
