# Generated by Django 4.1.2 on 2022-11-29 11:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(max_length=100, unique=True),
        ),
    ]
